# import data & feature creation
* input: file
* output: df_features, df_label

Data is from
https://www.eecs.qmul.ac.uk/mmv/datasets/deap/readme.html#prep

Know
1. https://pandas.pydata.org/pandas-docs/stable/generated/pandas.cut.html

In [1]:
import _pickle as cPickle

In [2]:
x = cPickle.load(open('data/data_preprocessed_python/s01.dat', 'rb'),encoding='bytes')

In [3]:
x.keys()

dict_keys([b'labels', b'data'])

In [20]:
arr_x = x[b'data']

In [5]:
y?

In [6]:
y.shape

(40, 40, 8064)

In [13]:
x[b'labels']

array([[ 7.71,  7.6 ,  6.9 ,  7.83],
       [ 8.1 ,  7.31,  7.28,  8.47],
       [ 8.58,  7.54,  9.  ,  7.08],
       [ 4.94,  6.01,  6.12,  8.06],
       [ 6.96,  3.92,  7.19,  6.05],
       [ 8.27,  3.92,  7.  ,  8.03],
       [ 7.44,  3.73,  7.08,  7.04],
       [ 7.32,  2.55,  6.32,  5.87],
       [ 4.04,  3.29,  3.62,  5.99],
       [ 1.99,  4.86,  2.04,  7.09],
       [ 2.99,  2.36,  3.63,  6.24],
       [ 2.71,  2.77,  3.4 ,  7.35],
       [ 1.95,  3.12,  2.87,  6.18],
       [ 4.18,  2.24,  3.04,  5.04],
       [ 3.17,  8.08,  2.91,  5.04],
       [ 6.81,  7.44,  8.15,  7.14],
       [ 2.46,  6.91,  6.77,  6.41],
       [ 7.23,  7.15,  6.94,  8.01],
       [ 7.17,  8.  ,  8.1 ,  6.79],
       [ 8.26,  7.91,  7.19,  8.13],
       [ 9.  ,  7.95,  8.37,  7.86],
       [ 7.09,  2.08,  7.06,  7.37],
       [ 8.15,  3.01,  7.37,  7.9 ],
       [ 7.04,  7.09,  8.01,  8.22],
       [ 8.86,  7.21,  8.65,  7.21],
       [ 7.28,  7.27,  7.41,  8.24],
       [ 7.35,  6.95,  7.03,  7.29],
 

In [7]:
import pandas as pd

In [8]:
df_label = pd.DataFrame(x[b'labels'])

df_label.columns = ['valence', 'arousal', 'dominance', 'liking']

df_label.drop(['dominance', 'liking'],axis=1,inplace=True)

df_label.valence = pd.cut(df_label.valence,bins=2,right=[0,5,10],labels=['high', 'low'])
df_label.arousal = pd.cut(df_label.arousal,bins=2,right=[0,5,10],labels=['high', 'low'])

df_label

In [21]:
arr_x = x[b'data']

## extract list

stats
1. mean
2. median
3. max
4. min
5. std dev
6. variance
7. range
8. skewness
9. kurtosis

from
1. 0:806, 10 batches
4. all


In [35]:
arr_x[0,:,:].shape

(40, 8064)

In [23]:
import scipy

In [27]:
from scipy.stats import skew, kurtosis

In [25]:
import numpy as np

In [44]:
STEPS = np.linspace(0,arr_x.shape[2]-1,11).astype(int); STEPS

ops = [np.mean, np.median, np.max, np.min ,np.std, np.var, skew, kurtosis]
# don't forget range

array([   0,  806, 1612, 2418, 3225, 4031, 4837, 5644, 6450, 7256, 8063])

In [46]:
np.mean(arr_x, axis=2).shape

(40, 40)

In [47]:
a = np.stack([op(arr_x, axis=2) for op in ops], axis=2);a.shape

(40, 40, 8)

In [51]:
A = a[:,:,2]-a[:,:,3]

In [52]:
A.shape

(40, 40)

In [59]:
# add range
a = np.dstack((a,a[:,:,2]-a[:,:,3]))

In [58]:
a1.shape

(40, 40, 9)

In [60]:
STEPS[1:]

array([ 806, 1612, 2418, 3225, 4031, 4837, 5644, 6450, 7256, 8063])

In [64]:
b = []
for start,end in zip(STEPS.tolist(),STEPS[1:].tolist()):
    ran = np.stack([op(arr_x[:,:,start:end], axis=2) for op in ops], axis=2)
    ran = np.dstack((ran,ran[:,:,2]-ran[:,:,3]))
    b.append(ran)


b = np.concatenate(b,axis=2)

In [72]:
b.shape

(40, 40, 90)

In [79]:
PAT = 1

In [77]:
list(arr_x.shape[:2])+[1]

[40, 40, 1]

In [81]:
d = np.full(list(arr_x.shape[:2])+[1],PAT)

In [90]:
c = np.reshape(np.repeat(np.arange(arr_x.shape[0]), arr_x.shape[1]),list(arr_x.shape[:2])+[1])

In [91]:
features = np.concatenate((a,b,c,d),axis=2)

In [92]:
features.shape

(40, 40, 101)

In [94]:
df_label = pd.get_dummies(df_label)

In [95]:
df_label

valence_high  valence_low  arousal_high  arousal_low
0              0            1             0            1
1              0            1             0            1
2              0            1             0            1
3              1            0             0            1
4              0            1             1            0
5              0            1             1            0
6              0            1             1            0
7              0            1             1            0
8              1            0             1            0
9              1            0             1            0
10             1            0             1            0
11             1            0             1            0
12             1            0             1            0
13             1            0             1            0
14             1            0             0            1
15             0            1             0            1
16             1            0             0            1
17             0            1             0            1
18             0            1             0            1
19             0            1             0            1
20             0            1             0            1
21             0            1             1            0
22             0            1             1            0
23             0            1             0            1
24             0            1             0            1
25             0            1             0            1
26             0            1             0            1
27             1            0             1            0
28             1            0             1            0
29             1            0             1            0
30             1            0             0            1
31             1            0             0            1
32             1            0             1            0
33             1            0             0            1
34             1            0             0            1
35             1            0             0            1
36             1            0             0            1
37             1            0             0            1
38             1            0             0            1
39             1            0             0            1

## applied for each file

In [96]:
from glob import glob

In [100]:
import os, re

In [101]:
files = glob('data/data_preprocessed_python/*.dat')

In [103]:
PAT = re.search(r"\d+",os.path.basename(files[0]))

In [108]:
int(PAT.group(0))

28

In [109]:
int('01')

1

In [98]:
def readDEAPFile(file):
    with open(file, 'rb') as f:
        x = cPickle.load(f,encoding='bytes')
    return x[b'data'], x[b'labels']
    

In [112]:
def processDEAP(file):
    PAT = re.search(r"\d+",os.path.basename(file))
    PAT = int(PAT.group(0))
    
    arr_x, y = readDEAPFile(file)
    
    # label process
    df_label = pd.DataFrame(y)

    df_label.columns = ['valence', 'arousal', 'dominance', 'liking']

    df_label.drop(['dominance', 'liking'],axis=1,inplace=True)

    df_label.valence = pd.cut(df_label.valence,bins=2,right=[0,5,10],labels=['high', 'low'])
    df_label.arousal = pd.cut(df_label.arousal,bins=2,right=[0,5,10],labels=['high', 'low'])
    df_label = pd.get_dummies(df_label)
    
    
    # features process
    STEPS = np.linspace(0,arr_x.shape[2]-1,11).astype(int); STEPS

    ops = [np.mean, np.median, np.max, np.min ,np.std, np.var, skew, kurtosis] # not include range
    
    # features process: all
    a = np.stack([op(arr_x, axis=2) for op in ops], axis=2)
    a = np.dstack((a,a[:,:,2]-a[:,:,3]))
    
    # features process: the 10-batch
    b = []
    for start,end in zip(STEPS.tolist(),STEPS[1:].tolist()):
        ran = np.stack([op(arr_x[:,:,start:end], axis=2) for op in ops], axis=2)
        ran = np.dstack((ran,ran[:,:,2]-ran[:,:,3]))
        b.append(ran)
    b = np.concatenate(b,axis=2)
    
    # features process: identities
    c = np.reshape(np.repeat(np.arange(arr_x.shape[0]), arr_x.shape[1]),list(arr_x.shape[:2])+[1])
    d = np.full(list(arr_x.shape[:2])+[1],PAT)
    
    features = np.concatenate((a,b,c,d),axis=2)
    
    return features, df_label

In [113]:
xs = []
dfs_y = []
for file in files:
    x, df_y = processDEAP(file)
    xs.append(x)
    dfs_y.append(df_y)

In [115]:
xs = np.stack(xs)

In [117]:
xs.shape # paticipant, experiment, ch, data

(32, 40, 40, 101)

In [118]:
ys = [df.values for df in dfs_y]
ys = np.stack(ys)

In [120]:
ys.shape # paticipant, experiment, label

(32, 40, 4)

# save and load

In [123]:
import pickle

In [127]:
with open('data/x.dat',mode='wb') as f:
    pickle.dump(xs, f)
with open('data/y.dat',mode='wb') as f:
    pickle.dump(ys, f)

In [ ]:
with open('data/x.dat', mode='rb') as f:
    xs = pickle.load(f)
with open('data/y.dat', mode='rb') as f:
    ys = pickle.load(f)

# Create the network

In [125]:
import keras

Using TensorFlow backend.


In [147]:
from keras.models import Sequential
from keras.layers import Conv2D, Flatten, Dense, Dropout, MaxPool2D
from keras.optimizers import SGD

In [165]:
batchSize = 50
nbClasses = 2
nbEpoch = 5
CH, DATA = 40, 101
nbFilters = 100
nbConv = 3
NEpoch = 50

In [166]:
model = Sequential()

model.add(Convolution2D(nbFilters, (nbConv, nbConv), input_shape=(1,CH,DATA), activation='tanh', data_format='channels_first'))
model.add(Convolution2D(nbFilters, (nbConv, nbConv), activation='tanh'))
model.add(MaxPool2D())
model.add(Dropout(0.5))
model.add(Flatten())
model.add(Dense(128, activation='tanh'))
model.add(Dropout(0.25))
model.add(Dense(nbClasses, activation='softplus'))

sgd = SGD(lr=0.00001, decay= 1e-6, momentum= 0.9, nesterov=True)

model.compile(sgd, 'categorical_crossentropy')



In [159]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_16 (Conv2D)           (None, 100, 38, 99)       1000      
_________________________________________________________________
conv2d_17 (Conv2D)           (None, 98, 36, 100)       89200     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 49, 18, 100)       0         
_________________________________________________________________
dropout_3 (Dropout)          (None, 49, 18, 100)       0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 88200)             0         
_________________________________________________________________
dense_3 (Dense)              (None, 128)               11289728  
_________________________________________________________________
dropout_4 (Dropout)          (None, 128)               0         
__________

In [168]:
pat, exp, ch ,data = xs.shape
X = xs.reshape(pat*exp, 1, ch, data); X.shape

(1280, 1, 40, 101)

In [170]:
pat, exp, label = ys.shape
Y = ys.reshape(pat*exp,-1)[:,:2]; Y.shape

(1280, 2)

In [171]:
accAll = []
for _ in range(NEpoch):
    model.fit(X,Y,batch_size=batchSize, epochs=nbEpoch, validation_split=1/32)

Train on 1240 samples, validate on 40 samples
Epoch 1/5
1240/1240 [==============================] - 52s - loss: 0.8399 - val_loss: 0.6960
Epoch 2/5
1240/1240 [==============================] - 54s - loss: 0.7954 - val_loss: 0.6933
Epoch 3/5
1240/1240 [==============================] - 53s - loss: 0.7362 - val_loss: 0.6976
Epoch 4/5
1240/1240 [==============================] - 53s - loss: 0.7463 - val_loss: 0.6916
Epoch 5/5
1240/1240 [==============================] - 52s - loss: 0.7354 - val_loss: 0.6943
Train on 1240 samples, validate on 40 samples
Epoch 1/5
1240/1240 [==============================] - 53s - loss: 0.7120 - val_loss: 0.6909
Epoch 2/5
1240/1240 [==============================] - 52s - loss: 0.7158 - val_loss: 0.6918
Epoch 3/5
1240/1240 [==============================] - 52s - loss: 0.7094 - val_loss: 0.6871
Epoch 4/5
1240/1240 [==============================] - 62s - loss: 0.7002 - val_loss: 0.6882
Epoch 5/5
1240/1240 [==============================] - 55s - loss: 0.69

1240/1240 [==============================] - 53s - loss: 0.6827 - val_loss: 0.6839
Epoch 2/5
1240/1240 [==============================] - 53s - loss: 0.6826 - val_loss: 0.6824
Epoch 3/5
1240/1240 [==============================] - 53s - loss: 0.6778 - val_loss: 0.6829
Epoch 4/5
1240/1240 [==============================] - 53s - loss: 0.6814 - val_loss: 0.6831
Epoch 5/5
1240/1240 [==============================] - 53s - loss: 0.6802 - val_loss: 0.6838
Train on 1240 samples, validate on 40 samples
Epoch 1/5
1240/1240 [==============================] - 53s - loss: 0.6811 - val_loss: 0.6862
Epoch 2/5
1240/1240 [==============================] - 53s - loss: 0.6854 - val_loss: 0.6837
Epoch 3/5
1240/1240 [==============================] - 53s - loss: 0.6833 - val_loss: 0.6821
Epoch 4/5
1240/1240 [==============================] - 53s - loss: 0.6808 - val_loss: 0.6830
Epoch 5/5
1240/1240 [==============================] - 53s - loss: 0.6744 - val_loss: 0.6813
Train on 1240 samples, validate on

1240/1240 [==============================] - 55s - loss: 0.6620 - val_loss: 0.6736
Epoch 2/5
1240/1240 [==============================] - 55s - loss: 0.6716 - val_loss: 0.6733
Epoch 3/5
1240/1240 [==============================] - 55s - loss: 0.6702 - val_loss: 0.6739
Epoch 4/5
1240/1240 [==============================] - 55s - loss: 0.6656 - val_loss: 0.6743
Epoch 5/5
1240/1240 [==============================] - 55s - loss: 0.6768 - val_loss: 0.6724
Train on 1240 samples, validate on 40 samples
Epoch 1/5
1240/1240 [==============================] - 56s - loss: 0.6724 - val_loss: 0.6737
Epoch 2/5
1240/1240 [==============================] - 57s - loss: 0.6704 - val_loss: 0.6741
Epoch 3/5
1240/1240 [==============================] - 55s - loss: 0.6673 - val_loss: 0.6737
Epoch 4/5
1240/1240 [==============================] - 55s - loss: 0.6601 - val_loss: 0.6719
Epoch 5/5
1240/1240 [==============================] - 54s - loss: 0.6755 - val_loss: 0.6722
Train on 1240 samples, validate on

1240/1240 [==============================] - 51s - loss: 0.6426 - val_loss: 0.6708
Epoch 2/5
1240/1240 [==============================] - 51s - loss: 0.6402 - val_loss: 0.6700
Epoch 3/5
1240/1240 [==============================] - 51s - loss: 0.6544 - val_loss: 0.6671
Epoch 4/5
1240/1240 [==============================] - 51s - loss: 0.6580 - val_loss: 0.6674
Epoch 5/5
1240/1240 [==============================] - 51s - loss: 0.6387 - val_loss: 0.6684
Train on 1240 samples, validate on 40 samples
Epoch 1/5
1240/1240 [==============================] - 51s - loss: 0.6524 - val_loss: 0.6687
Epoch 2/5
1240/1240 [==============================] - 51s - loss: 0.6503 - val_loss: 0.6685
Epoch 3/5
1240/1240 [==============================] - 51s - loss: 0.6381 - val_loss: 0.6686
Epoch 4/5
1240/1240 [==============================] - 51s - loss: 0.6472 - val_loss: 0.6683
Epoch 5/5
1240/1240 [==============================] - 51s - loss: 0.6322 - val_loss: 0.6678


In [151]:
ys.shape

(32, 40, 4)

In [172]:
model.evaluate(X,Y)

1280/1280 [==============================] - 22s    


0.60726239234209056

In [173]:
model.save('originalNet.h5')